import Head from 'next/head'
import { Inter } from '@next/font/google'
import { React } from 'react';

import Navbar from '@/components/Navbar';

import style from '@/styles/Home.module.css'
import HeroSection from '@/components/HeroSection';
import WhyUs from '@/components/WhyUs';
import Footer from '@/components/Footer';
import Campaigns from '@/components/Campaigns';
import HowToPlay from '@/components/HowToPlay';
import MobileApp from '@/components/MobileApp';
import LiveCompaign from '@/components/LiveCompaign';

const inter = Inter({ subsets: ['latin'] });




export default function Home() {
  return (
    <>
      <Head>
        <title>Lottery App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <HeroSection />
      <Campaigns />
      <MobileApp />
      <LiveCompaign />

      <WhyUs />
      <HowToPlay />
      <Footer />



      






    </>
  )
}
